dataset:
  data_path: 'D:/dataset/AVE_Dataset/AVE_1fps_mid'
  data_json_path: 'D:/dataset/AVE_Dataset/av_1fps.json'
  finetune_json_path: 'D:/dataset/AVE_Dataset/{}.json'

  target_length: 96
  num_mel_bins: 128
  use_fbank: False
  fbank_dir: ''
  freqm: 0
  timem: 0
  norm_mean: -4.2677393
  norm_std: 4.5689974
  roll_mag_aug: True

model:
  model_name: 'mae_vit_base_patch16'
#  model_name: 'mae_vit_large_patch16'

  audiomae_pretrained_pth_path: 'E:/Research/AVQA/lib/pretrained.pth'
  pretrained_audio_mae_path: 'D:/dataset/AVE_Dataset/audiomae.pth'
  pretrained_vig_path: 'D:/dataset/AVE_Dataset/vig_b_82.6.pth'


train:
  visible_gpu: '0'
  device: 'cuda'
  batch_accum: 1
  batch_size: 24
  num_workers: 4
  pin_memory: True

  training_mode: True
  test_epoch: 1

  start_epoch: 1
  start_test_epoch: 2
  start_save_epoch: 1
  test_freq: 1 # test how many epoch
  save_freq: 1
  epochs: 10
  log_freq: 10 # log how many loss per epoch
  lr: 0.0002

  use_augment: False

distributed:
  dist: True
  rank: 0
  local_rank: -1
  world_size: 1
  init_method: "tcp://127.0.0.1:23333"
  backend: "gloo"