dataset:
  data_path: 'D:/dataset/AVE_Dataset/AVE_1fps_mid'
  data_json_path: 'D:/dataset/AVE_Dataset/av_1fps.json'
  finetune_json_path: 'D:/dataset/AVE_Dataset/{}.json'

  target_length: 96
  num_mel_bins: 128
  use_fbank: False
  fbank_dir: ''
  freqm: 0
  timem: 0
  norm_mean: -4.2677393
  norm_std: 4.5689974
  roll_mag_aug: True

model:
  model_name: 'mae_vit_base_patch16'
#  model_name: 'mae_vit_large_patch16'

  audiomae_pretrained_pth_path: 'E:/Research/AVQA/lib/pretrained.pth'
  pretrained_siammae_path: 'E:/Research/AVQA/models/siammae_pretrain/clip/ckp/model_2.pth'
  pretrained_audio_mae_path: 'D:/dataset/AVE_Dataset/audiomae.pth'
  pretrained_vig_path: 'D:/dataset/AVE_Dataset/vig_b_82.6.pth'

  mask_ratio: 0.8
  norm_pix_loss: False # Use (per-patch) normalized pixels as targets for computing loss
  in_channels: 1
  audio_exp: True
  alpha: 0 # contrastive loss weight
  omega: 1 # reconstruction loss weight
  mode: 0 # contrastive mode
  decoder_mode: 0 # decoder mode 0: global attn 1: swined local attn
  use_custom_patch: False # use custom patch and override timm PatchEmbed
  split_pos: False # use splitted pos emb
  pos_trainable: False
  use_nce: False
  load_video: False
  mask_2d: False # use 2d masking
  mask_t_prob: 0.7 # ratio of masking time
  mask_f_prob: 0.3 # ratio of masking frequency
  no_shift: False

  select_num: 10
  fix_select: True
  answer_types: 29
  lstm_layers: 4
  dropout: 0.0

  finetune:
    image_mae: False
    image_mae_proj: True
    audio_mae: False
    audio_mae_proj: True
    clip_text: False
    clip_text_proj: False

train:
  visible_gpu: '0'
  device: 'cuda'
  batch_accum: 1
  batch_size: 24
  num_workers: 4
  pin_memory: True

  training_mode: True
  test_epoch: 1

  start_epoch: 1
  start_test_epoch: 2
  start_save_epoch: 1
  test_freq: 1 # test how many epoch
  save_freq: 1
  epochs: 10
  log_freq: 10 # log how many loss per epoch
  lr: 0.0002

  use_augment: False

distributed:
  dist: True
  rank: 0
  local_rank: -1
  world_size: 1
  init_method: "tcp://127.0.0.1:23333"
  backend: "gloo"